### ISSUE TITLE
No sound (snd_soc_rt5651)

### ISSUE THREAD

**Issue by bartman081523** [hjgode/trekstor_surftab_duo_w1#1]
Thanks for your tutorial. 
Have you got sound to work? The module is snd_soc_rt5651.
I have tried setting this in `/etc/modprobe.d/intel-sof.conf`

`options snd_sof sof_debug=1`
and/or this
`options snd-intel-dspcfg dsp_driver=2`

and also I have install updated snd_sof firmware from github, 
this works in 22.04, but apparently not in 20.04
I will now try to install official firmware package for sound (firmware-sof-signed)
[firmware-sof-signed](https://packages.ubuntu.com/firmware-sof-signed)

**Comment by hjgode** [comment]
As the tablet behaves very slow I switched it back to windows. I am sorry, but I cannot help further.
